---
- name: Install Chocolatey and apps on Windows machines
  hosts: windows
  gather_facts: no
  tasks:

    - name: Ensure Chocolatey is installed
      ansible.windows.win_chocolatey:
        name: chocolatey
        state: present
        source: https://community.chocolatey.org/install.ps1

    - name: Install applications using Chocolatey
      ansible.windows.win_chocolatey:
        name: "{{ item }}"
        state: present
      loop:
        - putty
        - googlechrome
        - vscode

