---
- name: "Install PuTTY"
  hosts: 10.250.5.47
  gather_facts: false
  
  collections:
    - ansible.windows

  tasks:
    - name: Install PuTTY
      win_chocolatey:
        name: putty
        state: present
