---
- name: "Run setup_putty.ps1 on remote Windows machine"
  hosts: 10.250.5.47  
  gather_facts: false
  tasks:
    - name: Run setup_putty.ps1 PowerShell script
      win_shell: powershell.exe -ExecutionPolicy Bypass -File C:\Temp\setup_putty.ps1

