- name: NotePad++ installation on MMCS-WIN-01
  hosts: 10.250.5.116
  gather_facts: false
  tasks:
    - name: Install Notepad++ with Chocolatey module
      win_chocolatey:
        name: notepadplusplus
        state: latest
        ignore_checksum: yes
        force: true
