---
- name: Test Chocolatey Management
  hosts: 10.200.5.124
  gather_facts: no
  collections:
    - chocolatey.chocolatey
  tasks:
    - name: Ensure Chocolatey is installed
      chocolatey.chocolatey.win_chocolatey:
        name: chocolatey
        state: present



