---
- name: "Install Chocolatey and Google Chrome"
  hosts: 10.250.5.47
  gather_facts: false
  
  collections:
    - ansible.windows

  tasks:
    - name: Install Chocolatey and core extension
      win_chocolatey:
        name:
          - chocolatey
          - chocolatey-core.extension
        state: present

    - name: Kill running Chrome processes
      win_shell: |
        Stop-Process -Name "chrome" -Force
      ignore_errors: yes

    - name: Install Google Chrome
      win_chocolatey:
        name: googlechrome
        state: latest
        ignore_checksums: yes
        force: true

